### ISSUE TITLE
[CSS] NavBar Not Responsive. Aditya Logo Important. 

### ISSUE THREAD

**Issue by Jiya-Ull-Haq** [GDSC-AEC/ICDECT#1]
## Big Desktop Screen  
<img width="1601" alt="Screenshot 2022-04-11 at 9 55 53 AM" src="https://user-images.githubusercontent.com/60106386/162665045-2c59101b-503d-4942-896a-99a8799f897a.png">

## Medium Desktop Screen  
<img width="1228" alt="Screenshot 2022-04-11 at 9 55 37 AM" src="https://user-images.githubusercontent.com/60106386/162665028-1ed0be1f-fa6b-43ce-a406-d4adfc21d4f1.png">

## Small Desktop Screen
<img width="1071" alt="Screenshot 2022-04-11 at 9 55 45 AM" src="https://user-images.githubusercontent.com/60106386/162665043-13c40b0c-7d9c-4a5f-a373-4e54591345dd.png">

## Mobile Screen  
<img width="496" alt="Screenshot 2022-04-11 at 10 01 21 AM" src="https://user-images.githubusercontent.com/60106386/162665710-0731d3dd-245b-43fb-8a15-6a9ef8443e0f.png">

**Comment by ishtiaqSamdani** [comment]
dne
