### ISSUE TITLE
Hero Height in Small Screens. 

### ISSUE THREAD

**Issue by Jiya-Ull-Haq** [GDSC-AEC/ICDECT#2]
<img width="496" alt="Screenshot 2022-04-11 at 10 01 21 AM" src="https://user-images.githubusercontent.com/60106386/162665562-721babfd-6534-4057-b0b3-44ee4009badb.png">

**Comment by ishtiaqSamdani** [comment]
it was a kind of a task really enjoyed it 🐱‍🏍
