### ISSUE TITLE
REMOVE Unwanted Links CAREFULLY

### ISSUE THREAD

**Issue by Jiya-Ull-Haq** [GDSC-AEC/icdect#3]
### Every HTML file has the same import links.
Some of which need not be in that specific HTML file. 
Due to this, The loading time reduces.  

<img width="986" alt="Screenshot 2022-04-11 at 10 13 10 AM" src="https://user-images.githubusercontent.com/60106386/162666407-1a68137e-cef1-4389-8b63-870dcf2c7210.png">

**Comment by HarshaSri-Sameera** [comment]
Created a pull request
